sudo: required
addons:
  chrome: stable

language: node_js

node_js:
  - "8.9.1"

before_install:
  - curl https://install.meteor.com | /bin/sh
  - export PATH="$HOME/.meteor:$PATH"

cache:
  directories:
    - $HOME/.meteor
    - $HOME/.npm
    - node_modules

notifications:
  email: false

before_script:
  - "export DISPLAY=:99.0"
  - meteor npm install
  - sleep 3

script:
  - meteor npm i --save-dev nightmare
  - TEST_BROWSER_DRIVER=nightmare meteor test --once --driver-package meteortesting:mocha --port 4000
