sudo: required
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js

node_js:
  - "11.14.0"

before_install:
  - curl https://install.meteor.com | /bin/sh
  - export PATH="$HOME/.meteor:$PATH"

cache:
  directories:
    - $HOME/.meteor
    - $HOME/.npm
    - node_modules

notifications:
  email: false

before_script:
  - "export DISPLAY=:99.0"
  - meteor npm install
  - sleep 3

script:
  - TEST_BROWSER_DRIVER=chrome meteor test --once --driver-package meteortesting:mocha
