language: node_js
node_js:
  - "stable"

cache:
  directories:
    - $HOME/.meteor
    - $HOME/.npm
    - node_modules

before_install:
  - curl https://install.meteor.com | /bin/sh
  - export PATH="$HOME/.meteor:$PATH"

before_script:
  - meteor npm install
