export const TOURNAMENT_MODE_CLASSIC = 'CLASSIC';
export const TOURNAMENT_MODE_HARDCORE = 'HARDCORE';
export const TOURNAMENT_MODE_RANDOM_BONUSES = 'RANDOM_BONUSES';
export const TOURNAMENT_MODE_SHAPE_SHIFT = 'SHAPE_SHIFT';
export const TOURNAMENT_MODE_DEATH_BONUS = 'DEATH_BONUS';
export const TOURNAMENT_MODE_SMOKE_BOMB = 'SMOKE_BOMB';
export const TOURNAMENT_MODE_SUDDEN_DEATH = 'SUDDEN_DEATH';
export const TOURNAMENT_MODE_SUPER_BOUNCE_WALLS = 'SUPER_BOUNCE_WALLS';
