export const BONUS_SMALL_BALL = 'SmallBallBonus';
export const BONUS_BIG_BALL = 'BigBallBonus';
export const BONUS_INVISIBLE_BALL = 'InvisibleBallBonus';
export const BONUS_CLONE_BALL = 'CloneBallBonus';
export const BONUS_CLEAR_BONUSES = 'ClearBonuses';
export const BONUS_SMALL_MONSTER = 'SmallMonsterBonus';
export const BONUS_BIG_MONSTER = 'BigMonsterBonus';
export const BONUS_BIG_JUMP_MONSTER = 'BigJumpMonsterBonus';
export const BONUS_SLOW_MONSTER = 'SlowMonsterBonus';
export const BONUS_FAST_MONSTER = 'FastMonsterBonus';
export const BONUS_FREEZE_MONSTER = 'FreezeMonsterBonus';
export const BONUS_UNFREEZE_MONSTER = 'UnfreezeMonsterBonus';
export const BONUS_REVERSE_MOVE_MONSTER = 'ReverseMoveMonsterBonus';
export const BONUS_INVINCIBLE_MONSTER = 'InvincibleMonsterBonus';
export const BONUS_INVISIBLE_MONSTER = 'InvisibleMonsterBonus';
export const BONUS_INVISIBLE_OPPONENT_MONSTER = 'InvisibleOpponentMonsterBonus';
export const BONUS_CLOUD = 'CloudBonus';
export const BONUS_BUMPERS = 'BumpersBonus';
export const BONUS_NO_JUMP_MONSTER = 'NoJumpMonsterBonus';
export const BONUS_BOUNCE_MONSTER = 'BounceMonsterBonus';
export const BONUS_CLOAKED_MONSTER = 'CloakedMonsterBonus';
export const BONUS_RANDOM = 'RandomBonus';
export const BONUS_SHAPE_SHIFT = 'ShapeShiftMonsterBonus';
export const BONUS_SMOKE_BOMB = 'SmokeBomb';
export const BONUS_INSTANT_DEATH = 'InstantDeath';
export const BONUS_REVIVE = 'ReviveBonus';
export const BONUS_INVINCIBLE_INSTANT_DEATH = 'InvincibleInstantDeathBonus';
export const BONUS_NOTHING = 'NothingBonus';
export const BONUS_REPELLENT = 'BonusRepellent';
export const BONUS_LOW_GRAVITY = 'LowGravity';
export const BONUS_HIGH_GRAVITY = 'HighGravity';
export const BONUS_POISON = 'Poison';
export const BONUS_CURE = 'Cure';
export const BONUS_ROBOT = 'Robot';
export const BONUS_RESET_BALL_HIT_COUNT = 'ResetBallHitCountBonus';

export const ALL_BONUSES = [
	BONUS_RANDOM,
	BONUS_CLOUD,
	BONUS_SMOKE_BOMB,
	BONUS_BUMPERS,
	BONUS_SMALL_BALL,
	BONUS_BIG_BALL,
	BONUS_INVISIBLE_BALL,
	BONUS_CLONE_BALL,
	BONUS_LOW_GRAVITY,
	BONUS_HIGH_GRAVITY,
	BONUS_CLEAR_BONUSES,
	BONUS_NOTHING,
	BONUS_SMALL_MONSTER,
	BONUS_BIG_MONSTER,
	BONUS_REVERSE_MOVE_MONSTER,
	BONUS_SLOW_MONSTER,
	BONUS_FAST_MONSTER,
	BONUS_NO_JUMP_MONSTER,
	BONUS_BIG_JUMP_MONSTER,
	BONUS_BOUNCE_MONSTER,
	BONUS_FREEZE_MONSTER,
	BONUS_UNFREEZE_MONSTER,
	BONUS_INVISIBLE_MONSTER,
	BONUS_INVISIBLE_OPPONENT_MONSTER,
	BONUS_CLOAKED_MONSTER,
	BONUS_SHAPE_SHIFT,
	BONUS_REPELLENT,
	BONUS_INVINCIBLE_MONSTER,
	BONUS_INSTANT_DEATH,
	BONUS_REVIVE,
	BONUS_INVINCIBLE_INSTANT_DEATH,
	BONUS_POISON,
	BONUS_CURE,
	BONUS_ROBOT,
	BONUS_RESET_BALL_HIT_COUNT,
];

export const ALL_BONUSES_FOR_RANDOM = [
	BONUS_CLOUD,
	BONUS_SMOKE_BOMB,
	BONUS_BUMPERS,
	BONUS_SMALL_BALL,
	BONUS_BIG_BALL,
	BONUS_INVISIBLE_BALL,
	BONUS_CLONE_BALL,
	BONUS_LOW_GRAVITY,
	BONUS_HIGH_GRAVITY,
	BONUS_CLEAR_BONUSES,
	BONUS_NOTHING,
	BONUS_SMALL_MONSTER,
	BONUS_BIG_MONSTER,
	BONUS_REVERSE_MOVE_MONSTER,
	BONUS_SLOW_MONSTER,
	BONUS_FAST_MONSTER,
	BONUS_NO_JUMP_MONSTER,
	BONUS_BIG_JUMP_MONSTER,
	BONUS_BOUNCE_MONSTER,
	BONUS_FREEZE_MONSTER,
	BONUS_UNFREEZE_MONSTER,
	BONUS_INVISIBLE_MONSTER,
	BONUS_INVISIBLE_OPPONENT_MONSTER,
	BONUS_CLOAKED_MONSTER,
	BONUS_SHAPE_SHIFT,
	BONUS_REPELLENT,
	BONUS_INVINCIBLE_MONSTER,
	BONUS_INSTANT_DEATH,
	BONUS_REVIVE,
	BONUS_INVINCIBLE_INSTANT_DEATH,
	BONUS_POISON,
	BONUS_CURE,
	BONUS_ROBOT,
	BONUS_RESET_BALL_HIT_COUNT,
];
