export const PLAYER_INTERVAL = 30;
export const BALL_INTERVAL = 30;
export const BONUS_INTERVAL = 30;
export const BONUS_SPAWN_MINIMUM_FREQUENCE = 2000;
export const BONUS_SPAWN_INITIAL_MINIMUM_FREQUENCE = 10000;
export const BONUS_SPAWN_INITIAL_MAXIMUM_FREQUENCE = 15000;
export const BONUS_DURATION = 10000;
