export const PLAYER_SHAPE_RANDOM = 'random';
export const PLAYER_SHAPE_HALF_CIRCLE = 'half-circle';
export const PLAYER_SHAPE_TRIANGLE = 'triangle';
export const PLAYER_SHAPE_X = 'x';
export const PLAYER_SHAPE_RECTANGLE = 'rectangle';
export const PLAYER_SHAPE_EQUAL = 'equal';
export const PLAYER_SHAPE_MAGNET = 'magnet';
export const PLAYER_SHAPE_CROWN = 'crown';
export const PLAYER_SHAPE_RHOMBUS = 'rhombus';
export const PLAYER_SHAPE_HEXAGON = 'hexagon';
export const PLAYER_SHAPE_DOT = 'dot';
export const PLAYER_SHAPE_ELLIPSE = 'ellipse';
export const PLAYER_SHAPE_TRIPLE_COLON = 'triple-colon';
export const PLAYER_DEFAULT_SHAPE = PLAYER_SHAPE_HALF_CIRCLE;
export const PLAYER_LIST_OF_SHAPES = [
	PLAYER_SHAPE_HALF_CIRCLE,
	PLAYER_SHAPE_TRIANGLE,
	PLAYER_SHAPE_X,
	PLAYER_SHAPE_RECTANGLE,
	PLAYER_SHAPE_EQUAL,
	PLAYER_SHAPE_MAGNET,
	PLAYER_SHAPE_CROWN,
	PLAYER_SHAPE_RHOMBUS,
	PLAYER_SHAPE_HEXAGON,
	PLAYER_SHAPE_DOT,
	PLAYER_SHAPE_ELLIPSE,
	PLAYER_SHAPE_TRIPLE_COLON
];
export const PLAYER_ALLOWED_LIST_OF_SHAPES = [PLAYER_SHAPE_RANDOM].concat(PLAYER_LIST_OF_SHAPES);
