Constants = {
	GAME_STATUS_REGISTRATION: 'registration',
	GAME_STATUS_STARTED: 'started',
	GAME_STATUS_TIMEOUT: 'timeout',
	GAME_STATUS_FINISHED: 'finished',

	HOST_POINTS_COLUMN: 'hostPoints',
	CLIENT_POINTS_COLUMN: 'clientPoints',

	LAST_POINT_TAKEN_HOST: 'host',
	LAST_POINT_TAKEN_CLIENT: 'client',

	PLAYER_SHAPE_HALF_CIRCLE: 'half-circle',
	PLAYER_SHAPE_TRIANGLE: 'triangle',
	PLAYER_SHAPE_RECTANGLE: 'rectangle',
	PLAYER_SHAPE_RHOMBUS: 'rhombus',
	PLAYER_SHAPE_HEXAGON: 'hexagon'
};

Constants.PLAYER_DEFAULT_SHAPE = Constants.PLAYER_SHAPE_HALF_CIRCLE;
Constants.PLAYER_LIST_OF_SHAPES = [
	Constants.PLAYER_SHAPE_HALF_CIRCLE,
	Constants.PLAYER_SHAPE_TRIANGLE,
	Constants.PLAYER_SHAPE_RECTANGLE,
	Constants.PLAYER_SHAPE_RHOMBUS,
	Constants.PLAYER_SHAPE_HEXAGON
];
