Constants = {
	GAME_STATUS_REGISTRATION: 'registration',
	GAME_STATUS_STARTED: 'started',
	GAME_STATUS_TIMEOUT: 'timeout',
	GAME_STATUS_FINISHED: 'finished',

	HOST_POINTS_COLUMN: 'hostPoints',
	CLIENT_POINTS_COLUMN: 'clientPoints',

	LAST_POINT_TAKEN_HOST: 'host',
	LAST_POINT_TAKEN_CLIENT: 'client',

	PLAYER_SHAPE_HALF_CIRCLE: 'half-circle',
	PLAYER_SHAPE_TRIANGLE: 'triangle',
	PLAYER_SHAPE_RECTANGLE: 'rectangle',
	PLAYER_SHAPE_RHOMBUS: 'rhombus',
	PLAYER_SHAPE_HEXAGON: 'hexagon',

	TOO_SHORT_PASSWORD_ERROR_MESSAGE: 'Password must be at least 6 characters long',
	CONFIRMATION_MATCH_PASSWORD_ERROR_MESSAGE: 'The password confirmation must match the password',

	NORMAL_SCALE_BONUS: 1,
	NORMAL_SCALE_PHYSICS_DATA: 'physicsData',
	SMALL_SCALE_BONUS: 0.75,
	SMALL_SCALE_PHYSICS_DATA: 'physicsDataSmall',
	BIG_SCALE_BONUS: 1.5,
	BIG_SCALE_PHYSICS_DATA: 'physicsDataBig',

	BONUS_BIG_BALL: 'BigBallBonus',
	BONUS_BIG_MONSTER: 'BigMonsterBonus',
	BONUS_SMALL_MONSTER: 'SmallMonsterBonus'
};

Constants.PLAYER_DEFAULT_SHAPE = Constants.PLAYER_SHAPE_HALF_CIRCLE;
Constants.PLAYER_LIST_OF_SHAPES = [
	Constants.PLAYER_SHAPE_HALF_CIRCLE,
	Constants.PLAYER_SHAPE_TRIANGLE,
	Constants.PLAYER_SHAPE_RECTANGLE,
	Constants.PLAYER_SHAPE_RHOMBUS,
	Constants.PLAYER_SHAPE_HEXAGON
];
