import {
	BONUS_BIG_BALL,
	BONUS_BIG_JUMP_MONSTER,
	BONUS_BIG_MONSTER,
	BONUS_BOUNCE_MONSTER,
	BONUS_CLEAR_BONUSES, BONUS_CLOAKED_MONSTER,
	BONUS_CLONE_BALL,
	BONUS_FAST_MONSTER,
	BONUS_FREEZE_MONSTER,
	BONUS_HIGH_GRAVITY, BONUS_INVINCIBLE_MONSTER,
	BONUS_INVISIBLE_BALL,
	BONUS_INVISIBLE_MONSTER,
	BONUS_INVISIBLE_OPPONENT_MONSTER,
	BONUS_LOW_GRAVITY,
	BONUS_NO_JUMP_MONSTER, BONUS_POISON,
	BONUS_RANDOM, BONUS_RESET_BALL_HIT_COUNT,
	BONUS_SLOW_MONSTER,
	BONUS_SMALL_BALL,
	BONUS_SMALL_MONSTER
} from "../bonusConstants";
import GameOverrideMode from "./GameOverrideMode";

export default class TwoVersusTwoVolleyball implements GameOverrideMode {
	gameModeCode(): string {
		return '2vs2volleyball';
	}

	gameModeName(): string {
		return 'Volleyball';
	}

	isOneVersusOne(): boolean {
		return false;
	}

	isTwoVersusTwo(): boolean {
		return true;
	}

	gameOverride(): any {
		return {
			"overriddenPlayerMaximumBallHit": "1",
			"overriddenTeamMaximumBallHit": "3",
			"overriddenAvailableBonuses": [
				BONUS_RANDOM,
				BONUS_SMALL_BALL,
				BONUS_BIG_BALL,
				BONUS_INVISIBLE_BALL,
				BONUS_CLONE_BALL,
				BONUS_LOW_GRAVITY,
				BONUS_HIGH_GRAVITY,
				BONUS_CLEAR_BONUSES,
				BONUS_SMALL_MONSTER,
				BONUS_BIG_MONSTER,
				BONUS_SLOW_MONSTER,
				BONUS_FAST_MONSTER,
				BONUS_NO_JUMP_MONSTER,
				BONUS_BIG_JUMP_MONSTER,
				BONUS_BOUNCE_MONSTER,
				BONUS_FREEZE_MONSTER,
				BONUS_INVISIBLE_MONSTER,
				BONUS_INVISIBLE_OPPONENT_MONSTER,
				BONUS_CLOAKED_MONSTER,
				BONUS_POISON,
				BONUS_RESET_BALL_HIT_COUNT,
			],
			"overriddenAvailableBonusesForRandom": [
				BONUS_INVINCIBLE_MONSTER,
				BONUS_SMALL_BALL,
				BONUS_BIG_BALL,
				BONUS_INVISIBLE_BALL,
				BONUS_CLONE_BALL,
				BONUS_LOW_GRAVITY,
				BONUS_HIGH_GRAVITY,
				BONUS_CLEAR_BONUSES,
				BONUS_SMALL_MONSTER,
				BONUS_BIG_MONSTER,
				BONUS_SLOW_MONSTER,
				BONUS_FAST_MONSTER,
				BONUS_NO_JUMP_MONSTER,
				BONUS_BIG_JUMP_MONSTER,
				BONUS_BOUNCE_MONSTER,
				BONUS_FREEZE_MONSTER,
				BONUS_INVISIBLE_MONSTER,
				BONUS_INVISIBLE_OPPONENT_MONSTER,
				BONUS_CLOAKED_MONSTER,
				BONUS_POISON,
				BONUS_RESET_BALL_HIT_COUNT,
			],
		};
	}

	static create(): TwoVersusTwoVolleyball {
		return new TwoVersusTwoVolleyball();
	}
}
