import {
	BONUS_BIG_BALL,
	BONUS_BIG_JUMP_MONSTER,
	BONUS_BIG_MONSTER,
	BONUS_BOUNCE_MONSTER,
	BONUS_CLOAKED_MONSTER,
	BONUS_CLOUD,
	BONUS_FAST_MONSTER,
	BONUS_FREEZE_MONSTER,
	BONUS_HIGH_GRAVITY,
	BONUS_INVINCIBLE_INSTANT_DEATH,
	BONUS_INVISIBLE_BALL,
	BONUS_INVISIBLE_MONSTER,
	BONUS_INVISIBLE_OPPONENT_MONSTER,
	BONUS_LOW_GRAVITY,
	BONUS_NO_JUMP_MONSTER,
	BONUS_NOTHING,
	BONUS_POISON,
	BONUS_RANDOM,
	BONUS_REPELLENT,
	BONUS_REVERSE_MOVE_MONSTER,
	BONUS_SHAPE_SHIFT,
	BONUS_SLOW_MONSTER,
	BONUS_SMALL_BALL,
	BONUS_SMALL_MONSTER,
	BONUS_SMOKE_BOMB
} from '/imports/api/games/bonusConstants.js';
import Classic from './Classic';

export default class RandomBonuses extends Classic {
	overridesAvailableBonuses() {
		return true;
	}

	availableBonuses() {
		return [
			BONUS_RANDOM
		];
	}

	overridesAvailableBonusesForRandom() {
		return true;
	}

	availableBonusesForRandom() {
		return [
			BONUS_SMALL_BALL,
			BONUS_BIG_BALL,
			BONUS_INVISIBLE_BALL,
			BONUS_LOW_GRAVITY,
			BONUS_HIGH_GRAVITY,
			BONUS_SMALL_MONSTER,
			BONUS_BIG_MONSTER,
			BONUS_BIG_JUMP_MONSTER,
			BONUS_SLOW_MONSTER,
			BONUS_FAST_MONSTER,
			BONUS_FREEZE_MONSTER,
			BONUS_REVERSE_MOVE_MONSTER,
			BONUS_INVISIBLE_MONSTER,
			BONUS_INVISIBLE_OPPONENT_MONSTER,
			BONUS_INVINCIBLE_INSTANT_DEATH,
			BONUS_POISON,
			BONUS_REPELLENT,
			BONUS_CLOUD,
			BONUS_NO_JUMP_MONSTER,
			BONUS_BOUNCE_MONSTER,
			BONUS_CLOAKED_MONSTER,
			BONUS_SHAPE_SHIFT,
			BONUS_SMOKE_BOMB,
			BONUS_NOTHING,
		];
	}
}
